# Generated by Django 4.2.25 on 2025-11-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='pills_per_box',
        ),
    ]
