# Generated by Django 4.2.25 on 2025-11-05 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
