# Generated by Django 4.2.25 on 2025-11-04 10:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregivers', models.ManyToManyField(related_name='spaces', to='huproject.caregiver')),
                ('recipients', models.ManyToManyField(related_name='spaces', to='huproject.recipient')),
            ],
        ),
    ]
