# Generated by Django 4.2.25 on 2025-11-22 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0003_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creates', to=settings.AUTH_USER_MODEL),
        ),
    ]
