# Generated by Django 4.2.25 on 2025-11-07 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0004_space_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
