# Generated by Django 4.2.25 on 2025-11-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0005_recipient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='age',
        ),
    ]
