# Generated by Django 4.2.25 on 2025-11-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0005_alter_agendaitem_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='description',
        ),
    ]
