# Generated by Django 4.2.25 on 2025-11-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0006_remove_recipient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='recipients',
        ),
        migrations.AddField(
            model_name='recipient',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='huproject.space'),
            preserve_default=False,
        ),
    ]
