# Generated by Django 4.2.25 on 2025-11-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0006_remove_todolist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
