# Generated by Django 4.2.25 on 2025-11-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0007_remove_space_recipients_recipient_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='user',
        ),
    ]
