# Generated by Django 4.2.25 on 2025-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0007_alter_agendaitem_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitemcategory',
            name='name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
