# Generated by Django 4.2.25 on 2025-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0008_agendaitemcategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitemcategory',
            name='color',
            field=models.CharField(default='#007fff', max_length=15),
            preserve_default=False,
        ),
    ]
