# Generated by Django 4.2.25 on 2025-11-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0008_remove_recipient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='gender',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='gender',
            field=models.CharField(blank=True, null=True),
        ),
    ]
