# Generated by Django 4.2.25 on 2025-11-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0009_agendaitemcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitemcategory',
            name='color',
            field=models.JSONField(),
        ),
    ]
