# Generated by Django 4.2.25 on 2025-11-10 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0009_caregiver_gender_recipient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='huproject.space')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('used', models.BooleanField(default=False)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invites', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='huproject.space')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('private', models.BooleanField(default=False)),
                ('item_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='huproject.agenda')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creates', to='huproject.caregiver')),
                ('participants', models.ManyToManyField(related_name='participates', to='huproject.caregiver')),
                ('recipients', models.ManyToManyField(blank=True, related_name='participates', to='huproject.recipient')),
            ],
        ),
    ]
