# Generated by Django 4.2.25 on 2025-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0010_alter_agendaitemcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
