# Generated by Django 4.2.25 on 2025-11-10 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0010_agenda_spaceinvite_agendaitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendaitem',
            name='creator',
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creates', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
