# Generated by Django 4.2.25 on 2025-12-01 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0011_alter_agendaitem_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='caregivers',
        ),
        migrations.AddField(
            model_name='caregiver',
            name='space',
            field=models.ForeignKey(default='147447e9-53a2-4fd6-8fd3-6bf5bf159910', on_delete=django.db.models.deletion.CASCADE, related_name='caregivers', to='huproject.space'),
            preserve_default=False,
        ),
    ]
