# Generated by Django 4.2.25 on 2025-11-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0011_remove_agendaitem_creator_agendaitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
