# Generated by Django 4.2.25 on 2025-12-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0012_remove_space_caregivers_caregiver_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caregiver',
            name='space',
        ),
        migrations.AddField(
            model_name='space',
            name='caregivers',
            field=models.ManyToManyField(related_name='spaces', to='huproject.caregiver'),
        ),
    ]
