# Generated by Django 4.2.25 on 2025-12-07 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0013_remove_caregiver_space_space_caregivers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 1), ('admin', 2), ('editor', 3), ('reader', 4)])),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huproject.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
