# Generated by Django 4.2.25 on 2025-11-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0012_agendaitem_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='participants',
            field=models.ManyToManyField(related_name='participates', to='huproject.caregiver'),
        ),
    ]
