# Generated by Django 4.2.25 on 2025-11-12 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0014_alter_agendaitem_participants'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthcareProfessional',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agendaitem',
            name='item_type',
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_treatments', to='huproject.healthcareprofessional')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItemCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has', to='huproject.agenda')),
            ],
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='huproject.agendaitemcategory'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='healthcareProfessionals',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='huproject.healthcareprofessional'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='huproject.treatment'),
        ),
    ]
