# Generated by Django 4.2.25 on 2025-12-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0014_spacemembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.CharField(choices=[(1, 'owner'), (2, 'admin'), (3, 'editor'), (4, 'reader')]),
        ),
    ]
