# Generated by Django 4.2.25 on 2025-12-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0015_alter_spacemembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.IntegerField(choices=[('owner', 1), ('admin', 2), ('editor', 3), ('reader', 4)]),
        ),
    ]
