# Generated by Django 4.2.25 on 2025-11-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0015_healthcareprofessional_remove_agendaitem_item_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='healthcareProfessionals',
            new_name='healthcare_professionals',
        ),
    ]
