# Generated by Django 4.2.25 on 2025-11-15 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0016_rename_healthcareprofessionals_recipient_healthcare_professionals'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessional',
            name='space',
            field=models.ForeignKey(default='0a9d4255-17c6-497e-b577-eafcc04a448c', on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='huproject.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='space',
            field=models.ForeignKey(default='0a9d4255-17c6-497e-b577-eafcc04a448c', on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='huproject.space'),
            preserve_default=False,
        ),
    ]
