# Generated by Django 4.2.25 on 2025-11-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0017_healthcareprofessional_space_treatment_space'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='number_of_pills',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
    ]
