# Generated by Django 4.2.25 on 2025-11-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0018_treatment_number_of_pills'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='medication_format',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
