# Generated by Django 4.2.25 on 2025-12-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0018_alter_spacemembership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.CharField(choices=[(1, 'owner'), (2, 'admin'), (3, 'editor'), (4, 'reader')], default=4),
        ),
    ]
