# Generated by Django 4.2.25 on 2025-12-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0020_alter_spacemembership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'owner'), (2, 'admin'), (3, 'editor'), (4, 'reader')])),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted', models.BooleanField(default=False)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='huproject.space')),
            ],
        ),
        migrations.DeleteModel(
            name='SpaceInvite',
        ),
    ]
