# Generated by Django 4.2.25 on 2025-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0021_invitation_delete_spaceinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invited',
            field=models.BooleanField(default=False),
        ),
    ]
