# Generated by Django 4.2.25 on 2025-12-08 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0022_customuser_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(default='03601ebf-d5cc-4c45-9f46-d823375e712e', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
