# Generated by Django 4.2.25 on 2025-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0024_customuser_invited_by_acceptedinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invited_by',
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.IntegerField(choices=[(1, 'owner'), (2, 'admin'), (3, 'editor'), (4, 'reader')], default=2),
        ),
    ]
