# Generated by Django 4.2.25 on 2025-12-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0025_remove_customuser_invited_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='invited',
        ),
    ]
