# Generated by Django 4.2.25 on 2025-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0026_remove_customuser_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invited',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
