# Generated by Django 4.2.25 on 2025-12-13 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0027_customuser_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacemembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acceptedinvitation',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'editor'), (3, 'reader')]),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'editor'), (3, 'reader')]),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'editor'), (3, 'reader')], default=1),
        ),
    ]
