# Generated by Django 4.2.25 on 2025-12-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0028_spacemembership_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='gender',
            field=models.CharField(blank=True, default='N', null=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='gender',
            field=models.CharField(blank=True, default='N', null=True),
        ),
    ]
