# Generated by Django 4.2.25 on 2026-01-08 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0029_alter_caregiver_gender_alter_recipient_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedTreatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('medication_format', models.CharField(blank=True, max_length=100)),
                ('quantity', models.JSONField(blank=True, null=True)),
                ('frequency', models.JSONField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_archived_treatments', to='huproject.healthcareprofessional')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains_archives', to='huproject.space')),
            ],
        ),
    ]
