# Generated by Django 4.2.25 on 2026-01-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0030_archivedtreatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedtreatment',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
