# Generated by Django 4.2.25 on 2026-01-08 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0031_alter_archivedtreatment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedtreatment',
            name='treatment_id',
            field=models.CharField(default='ergwwetr349230gfu23g5u980fj32rf234f'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivedtreatment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
