# Generated by Django 4.2.25 on 2026-01-09 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0032_archivedtreatment_treatment_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='medication_format',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='prescribed_by',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='space',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='archivedtreatment',
            name='treatment_id',
        ),
        migrations.AddField(
            model_name='archivedtreatment',
            name='treatment',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='is_archived', to='huproject.treatment'),
            preserve_default=False,
        ),
    ]
