# Generated by Django 4.2.25 on 2026-01-09 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0033_remove_archivedtreatment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedtreatment',
            name='name',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
