# Generated by Django 4.2.25 on 2026-01-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0034_archivedtreatment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedtreatment',
            name='space',
            field=models.ForeignKey(default='147447e9-53a2-4fd6-8fd3-6bf5bf159910', on_delete=django.db.models.deletion.CASCADE, related_name='contains_archive', to='huproject.space'),
            preserve_default=False,
        ),
    ]
