# Generated by Django 4.2.25 on 2026-01-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0035_archivedtreatment_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivedtreatment',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_archived', to='huproject.treatment'),
        ),
    ]
