# Generated by Django 4.2.25 on 2026-01-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0036_alter_archivedtreatment_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='cis_code',
            field=models.CharField(default='63054036', max_length=10),
            preserve_default=False,
        ),
    ]
