# Generated by Django 4.2.25 on 2026-01-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0038_alter_todolist_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_space', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='huproject.agenda'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='huproject.agendaitemcategory'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='participants',
            field=models.ManyToManyField(related_name='caregiver_participants', to='huproject.caregiver'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='recipients_participants', to='huproject.recipient'),
        ),
        migrations.AlterField(
            model_name='agendaitemcategory',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='huproject.agenda'),
        ),
        migrations.AlterField(
            model_name='archivedtreatment',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_treatment_space', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='archivedtreatment',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='initial_treatment', to='huproject.treatment'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='healthcare_professional_space', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='caregivers',
            field=models.ManyToManyField(related_name='caregivers', to='huproject.caregiver'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='healthcare_professionals',
            field=models.ManyToManyField(blank=True, related_name='healthcare_professionnals', to='huproject.healthcareprofessional'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_space', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='treatments', to='huproject.treatment'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_space', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptor', to='huproject.healthcareprofessional'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_space', to='huproject.space'),
        ),
        migrations.CreateModel(
            name='Groceries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='huproject.caregiver')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to='huproject.recipient')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='space', to='huproject.space')),
            ],
        ),
    ]
