# Generated by Django 4.2.25 on 2026-01-12 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0039_alter_agenda_space_alter_agendaitem_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belongs_to', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='huproject.agenda'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='huproject.agendaitemcategory'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='participants',
            field=models.ManyToManyField(related_name='participates', to='huproject.caregiver'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='participates', to='huproject.recipient'),
        ),
        migrations.AlterField(
            model_name='agendaitemcategory',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has', to='huproject.agenda'),
        ),
        migrations.AlterField(
            model_name='archivedtreatment',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains_archive', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='archivedtreatment',
            name='treatment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='is_archived', to='huproject.treatment'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='caregivers',
            field=models.ManyToManyField(related_name='care_for', to='huproject.caregiver'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='healthcare_professionals',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='huproject.healthcareprofessional'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='treatments',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='huproject.treatment'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creates_todo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_treatments', to='huproject.healthcareprofessional'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contains', to='huproject.space'),
        ),
    ]
