# Generated by Django 4.2.25 on 2026-01-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0040_alter_agenda_space_alter_agendaitem_agenda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agendaitem',
            old_name='participants',
            new_name='caregivers',
        ),
    ]
