# Generated by Django 4.2.25 on 2026-01-24 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0041_rename_participants_agendaitem_caregivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_space', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='caregivers',
            field=models.ManyToManyField(related_name='agenda_caregivers', to='huproject.caregiver'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_item', to='huproject.agendaitemcategory'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='agenda_recipients', to='huproject.recipient'),
        ),
        migrations.AlterField(
            model_name='agendaitemcategory',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_item', to='huproject.agenda'),
        ),
    ]
