# Generated by Django 4.2.25 on 2026-01-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0042_alter_agenda_space_alter_agendaitem_caregivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_item', to='huproject.agenda'),
        ),
        migrations.AlterField(
            model_name='agendaitemcategory',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_category', to='huproject.agenda'),
        ),
    ]
