# Generated by Django 4.2.25 on 2026-01-24 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0043_alter_agendaitem_agenda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='caregivers',
            field=models.ManyToManyField(related_name='caregivers_item', to='huproject.caregiver'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='recipients_item', to='huproject.recipient'),
        ),
    ]
