# Generated by Django 4.2.25 on 2026-01-24 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0044_alter_agendaitem_caregivers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_space', to='huproject.space'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='agenda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_item', to='huproject.agenda'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_item', to='huproject.agendaitemcategory'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='created_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creator_item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agendaitemcategory',
            name='agenda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_category', to='huproject.agenda'),
        ),
    ]
