# Generated by Django 4.2.25 on 2026-01-24 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0046_alter_agendaitem_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitemcategory',
            name='agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_category', to='huproject.agenda'),
        ),
    ]
