# Generated by Django 4.2.25 on 2026-01-24 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0047_alter_agendaitemcategory_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_item', to='huproject.agendaitemcategory'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_item', to=settings.AUTH_USER_MODEL),
        ),
    ]
