# Generated by Django 4.2.25 on 2026-01-26 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0048_alter_agendaitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_space', to='huproject.space'),
        ),
    ]
