# Generated by Django 4.2.25 on 2026-01-26 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0049_alter_todolist_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='title',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='space',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='todo_space', to='huproject.space'),
        ),
        migrations.CreateModel(
            name='TodoListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frequency', models.CharField(default='punctual')),
                ('completed', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complete', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creates_todo', to=settings.AUTH_USER_MODEL)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_todo', to='huproject.todolist')),
            ],
        ),
    ]
