# Generated by Django 4.2.25 on 2026-01-28 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0050_remove_todolist_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipient',
            name='treatments',
        ),
        migrations.AddField(
            model_name='treatment',
            name='prescribed_to',
            field=models.ManyToManyField(related_name='treatments', to='huproject.recipient'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_treatments', to=settings.AUTH_USER_MODEL),
        ),
    ]
