# Generated by Django 4.2.25 on 2026-02-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0051_remove_recipient_treatments_treatment_prescribed_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='caregivers',
            field=models.ManyToManyField(related_name='caregivers_in', to='huproject.caregiver'),
        ),
    ]
