# Generated by Django 4.2.25 on 2026-02-11 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0052_alter_space_caregivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregiver',
            name='access_level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
