# Generated by Django 4.2.25 on 2026-02-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0053_alter_caregiver_access_level'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caregiver',
            constraint=models.CheckConstraint(check=models.Q(('access_level__lt', 4)), name='access_level_lt_4'),
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.CheckConstraint(check=models.Q(('role__lt', 4)), name='role_lt_4'),
        ),
    ]
