# Generated by Django 4.2.25 on 2026-02-12 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0054_caregiver_access_level_lt_4_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='spacemembership',
            name='role_lt_4',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'editor'), (3, 'reader')], validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='spacemembership',
            name='role',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'editor'), (3, 'reader')], default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.CheckConstraint(check=models.Q(('role__lt', 4)), name='invitation_role_lt_4'),
        ),
        migrations.AddConstraint(
            model_name='spacemembership',
            constraint=models.CheckConstraint(check=models.Q(('role__lt', 4)), name='membership_role_lt_4'),
        ),
    ]
