# Generated by Django 4.2.25 on 2026-02-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0055_remove_spacemembership_role_lt_4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
