# Generated by Django 4.2.25 on 2026-02-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0056_treatment_deleted_at_treatment_restored_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='restored_at',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='transaction_id',
        ),
        migrations.DeleteModel(
            name='ArchivedTreatment',
        ),
    ]
