# Generated by Django 4.2.25 on 2026-03-08 10:30

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0057_remove_treatment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='treatment',
            managers=[
                ('everything', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
