# Generated by Django 4.2.25 on 2026-03-08 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0058_alter_treatment_managers_treatment_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_space', to='huproject.space')),
                ('users', models.ManyToManyField(related_name='notifications_users', to='huproject.caregiver')),
            ],
        ),
        migrations.DeleteModel(
            name='Groceries',
        ),
    ]
