# Generated by Django 4.2.25 on 2026-03-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0059_notifications_delete_groceries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='invited',
            field=models.JSONField(null=True),
        ),
    ]
