# Generated by Django 4.2.25 on 2026-03-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0060_alter_customuser_invited'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
    ]
