# Generated by Django 4.2.25 on 2026-03-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0061_rename_notifications_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='expired_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
