# Generated by Django 4.2.25 on 2026-03-16 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0062_treatment_expired_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='users',
        ),
        migrations.AddField(
            model_name='notification',
            name='users',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_user', to='huproject.caregiver'),
            preserve_default=False,
        ),
    ]
