# Generated by Django 4.2.25 on 2026-03-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0063_remove_notification_users_notification_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='users',
            new_name='user',
        ),
    ]
