# Generated by Django 4.2.25 on 2026-03-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0064_rename_users_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='item',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Title', max_length=50),
            preserve_default=False,
        ),
    ]
