# Generated by Django 4.2.25 on 2026-03-17 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0065_notification_item_notification_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='item',
            new_name='reference_item',
        ),
    ]
