# Generated by Django 4.2.25 on 2026-03-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0066_rename_item_notification_reference_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
