# Generated by Django 4.2.25 on 2026-03-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0067_treatment_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='prescribed_to',
        ),
        migrations.AddField(
            model_name='treatment',
            name='prescribed_to',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='huproject.recipient'),
            preserve_default=False,
        ),
    ]
