# Generated by Django 4.2.25 on 2026-03-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0068_remove_treatment_prescribed_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='slug',
        ),
    ]
