# Generated by Django 4.2.25 on 2026-03-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0069_remove_treatment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='object_path',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
