# Generated by Django 4.2.25 on 2026-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0070_notification_object_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='reminder',
            field=models.JSONField(default=dict),
        ),
    ]
