# Generated by Django 4.2.25 on 2026-03-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0071_agendaitem_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
