# Generated by Django 4.2.25 on 2026-06-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0072_agendaitem_reminder_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='healthcare_professionals',
            field=models.ManyToManyField(blank=True, null=True, related_name='recipients', to='huproject.healthcareprofessional'),
        ),
    ]
