# Generated by Django 4.2.25 on 2026-06-18 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huproject', '0073_alter_recipient_healthcare_professionals'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='healthcare_professionals',
            field=models.ManyToManyField(blank=True, related_name='recipients', to='huproject.healthcareprofessional'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_user', to='huproject.caregiver')),
            ],
        ),
    ]
